import { useEffect, useMemo, useState } from 'react'
import { CalendarDays, Download, Home, Pencil, Radio, Save, Search, Settings, Trash2 } from 'lucide-react'
import { scheduleRules, sendungen as seedSendungen, type Sendung } from './data/seed'

type Page = 'Dashboard' | 'Sendungen' | 'Kalender' | 'Publikation' | 'Einstellungen'
type Form = Omit<Sendung, 'id'> & { id?: string }
type AppSettings = { organisationName: string; language: 'de' | 'it' | 'en'; logoText: string; logoImage: string; periodStart: string; periodEnd: string; viewMode: 'Tag' | 'Woche' | 'Monat' }
const defaults: AppSettings = { organisationName: 'Radio Maria Südtirol', language: 'de', logoText: 'R', logoImage: '', periodStart: '2023-11-01', periodEnd: '2023-12-31', viewMode: 'Woche' }
const emptyForm: Form = { title: '', category: '', language: 'de', source: 'local', active: true }
const pages: { label: Page; icon: typeof Home }[] = [{ label: 'Dashboard', icon: Home }, { label: 'Sendungen', icon: Radio }, { label: 'Kalender', icon: CalendarDays }, { label: 'Publikation', icon: Download }, { label: 'Einstellungen', icon: Settings }]
const rows = [['2023-11-01','Mittwoch','08:00','Heilige Messe','Live'],['2023-11-01','Mittwoch','09:00','Glaubensforum',''],['2023-11-02','Donnerstag','10:00','Lebenshilfe',''],['2023-11-03','Freitag','13:00','Im Focus',''],['2023-11-06','Montag','13:15','Bei uns zu Gast',''],['2023-12-02','Samstag','09:00','Adventtreffen','Sonderprogramm']]
function makeId(title: string) { return `snd_${title.toLowerCase().replaceAll(' ', '_')}` }
function saveFile(name: string, content: string, type = 'text/plain;charset=utf-8') { const blob = new Blob([content], { type }); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = name; a.click(); URL.revokeObjectURL(url) }

export function App() {
  const [page, setPage] = useState<Page>('Dashboard')
  const [query, setQuery] = useState('')
  const [form, setForm] = useState<Form>(emptyForm)
  const [notice, setNotice] = useState('')
  const [sendungen, setSendungen] = useState<Sendung[]>(() => JSON.parse(localStorage.getItem('rms.sendungen') || 'null') || seedSendungen)
  const [settings, setSettings] = useState<AppSettings>(() => ({ ...defaults, ...(JSON.parse(localStorage.getItem('rms.settings') || 'null') || {}) }))
  useEffect(() => localStorage.setItem('rms.sendungen', JSON.stringify(sendungen)), [sendungen])
  useEffect(() => localStorage.setItem('rms.settings', JSON.stringify(settings)), [settings])
  const filtered = useMemo(() => sendungen.filter((s) => `${s.title} ${s.category} ${s.source}`.toLowerCase().includes(query.toLowerCase())), [sendungen, query])
  const preview = rows.filter((r) => r[0] >= settings.periodStart && r[0] <= settings.periodEnd)
  function newSendung() { setPage('Sendungen'); setForm(emptyForm); setNotice('') }
  function editSendung(s: Sendung) { setPage('Sendungen'); setForm(s); setNotice('Sendung wird bearbeitet.') }
  function deleteSendung(id: string) { setSendungen(sendungen.filter((s) => s.id !== id)); setNotice('Sendung gelöscht.') }
  function saveSendung() { if (!form.title.trim()) { setNotice('Bitte einen Titel eingeben.'); return } const item: Sendung = { id: form.id || makeId(form.title), title: form.title.trim(), category: form.category || 'Ohne Kategorie', language: form.language, source: form.source || 'local', active: form.active }; setSendungen(sendungen.some((s) => s.id === item.id) ? sendungen.map((s) => s.id === item.id ? item : s) : [item, ...sendungen]); setForm(emptyForm); setNotice('Sendung gespeichert.') }
  function exportTxt() { saveFile('programmheft.txt', preview.map((r) => `${r[0]} ${r[1]}\n${r[2]} ${r[3]}${r[4] ? ` - ${r[4]}` : ''}`).join('\n\n')) }
  function exportAffinity() { saveFile('affinity-tags.txt', preview.map((r) => `<Monat>${r[0].slice(0,7)}</Monat>\n<Datum>${r[0]}</Datum>\n<Tag>${r[1]}</Tag>\n<Uhrzeit>${r[2]}</Uhrzeit>\n<Sendung>${r[3]}</Sendung>\n<Info>${r[4]}</Info>`).join('\n\n')) }
  function exportXml() { saveFile('programm.xml', `<programm von="${settings.periodStart}" bis="${settings.periodEnd}">\n${preview.map((r) => `  <sendung datum="${r[0]}" tag="${r[1]}" uhrzeit="${r[2]}"><titel>${r[3]}</titel><info>${r[4]}</info></sendung>`).join('\n')}\n</programm>`, 'application/xml') }
  function exportHtml() { saveFile('programm.html', `<h1>Programmheft</h1>${preview.map((r) => `<h2>${r[0]} ${r[1]}</h2><p><b>${r[2]}</b> ${r[3]} ${r[4]}</p>`).join('')}`, 'text/html') }
  function exportRds() { saveFile('rds.txt', preview.map((r) => `${r[2]}|${r[3]}`).join('\n')) }
  function exportJson() { saveFile('programm.json', JSON.stringify({ period: settings, preview, sendungen }, null, 2), 'application/json') }
  return <main className="app-shell"><aside className="sidebar"><div className="brand-block"><div className="brand-mark">{settings.logoImage ? <img src={settings.logoImage} alt="Logo"/> : settings.logoText}</div><div><p className="eyebrow">{settings.organisationName}</p><h1>RMS</h1></div></div><nav className="navigation">{pages.map((p) => { const Icon = p.icon; return <button key={p.label} className={page === p.label ? 'nav-item active' : 'nav-item'} onClick={() => setPage(p.label)}><Icon size={18}/><span>{p.label}</span></button> })}</nav><div className="sidebar-card"><p>Ausgabe</p><strong>{settings.periodStart} bis {settings.periodEnd}</strong></div></aside><section className="content-area"><header className="topbar"><div><p className="eyebrow">RMS</p><h2>{page}</h2></div><button className="primary-action" onClick={newSendung}>Neue Sendung</button></header>{page === 'Dashboard' && <Dashboard sendungen={sendungen} preview={preview} openCalendar={() => setPage('Kalender')} editSendung={editSendung}/>} {page === 'Sendungen' && <Sendungen filtered={filtered} query={query} setQuery={setQuery} form={form} setForm={setForm} saveSendung={saveSendung} deleteSendung={deleteSendung} editSendung={editSendung} notice={notice}/>} {page === 'Kalender' && <Kalender preview={preview} settings={settings} setSettings={setSettings}/>} {page === 'Publikation' && <Publikation exportTxt={exportTxt} exportJson={exportJson} exportAffinity={exportAffinity} exportXml={exportXml} exportHtml={exportHtml} exportRds={exportRds}/>} {page === 'Einstellungen' && <Einstellungen settings={settings} setSettings={setSettings} reset={() => { localStorage.clear(); location.reload() }}/>}</section></main>
}
function Dashboard({ sendungen, preview, openCalendar, editSendung }: { sendungen: Sendung[]; preview: string[][]; openCalendar: () => void; editSendung: (s: Sendung) => void }) { return <><section className="hero-panel"><div><p className="eyebrow">Aktueller Arbeitsstand</p><h3>Programmheft November-Dezember</h3><p>{preview.length} Programmpunkte in der aktuellen Export-Vorschau.</p></div><button className="hero-action" onClick={openCalendar}>Programm bearbeiten</button></section><section className="main-grid"><article className="panel"><div className="panel-header"><div><p className="eyebrow">Vorschau</p><h3>Exportzeitraum</h3></div></div><Preview rows={preview}/></article><article className="panel"><div className="panel-header"><div><p className="eyebrow">Sendungen</p><h3>Katalog</h3></div></div><div className="sendung-list">{sendungen.slice(0,8).map((s) => <button className="sendung-row" key={s.id} onClick={() => editSendung(s)}><div><strong>{s.title}</strong><p>{s.category}</p></div><span>{s.source}</span></button>)}</div></article></section></> }
function Preview({ rows }: { rows: string[][] }) { return <div className="timeline">{rows.map((r) => <div className="timeline-row" key={`${r[0]}${r[2]}`}><time>{r[2]}</time><div className="timeline-node"/><div><strong>{r[0]} · {r[1]} · {r[3]}</strong><p>{r[4]}</p></div></div>)}</div> }
function Sendungen(p: { filtered: Sendung[]; query: string; setQuery: (v: string) => void; form: Form; setForm: (f: Form) => void; saveSendung: () => void; deleteSendung: (id: string) => void; editSendung: (s: Sendung) => void; notice: string }) { return <section className="workspace-grid"><article className="panel"><div className="panel-header"><div><p className="eyebrow">Katalog</p><h3>Sendungen verwalten</h3></div><div className="search-box"><Search size={16}/><input value={p.query} onChange={(e) => p.setQuery(e.target.value)} placeholder="Suchen"/></div></div><div className="table-list">{p.filtered.map((s) => <div className="table-row" key={s.id}><div><strong>{s.title}</strong><p>{s.category} · {s.source}</p></div><div className="row-actions"><button onClick={() => p.editSendung(s)}><Pencil size={16}/> Bearbeiten</button><button className="danger" onClick={() => p.deleteSendung(s.id)}><Trash2 size={16}/> Löschen</button></div></div>)}</div></article><article className="panel form-panel"><div className="panel-header"><div><p className="eyebrow">Formular</p><h3>{p.form.id ? 'Sendung bearbeiten' : 'Neue Sendung'}</h3></div></div><label>Titel<input value={p.form.title} onChange={(e) => p.setForm({...p.form, title: e.target.value})}/></label><label>Kategorie<input value={p.form.category} onChange={(e) => p.setForm({...p.form, category: e.target.value})}/></label><label>Quelle<input value={p.form.source} onChange={(e) => p.setForm({...p.form, source: e.target.value})}/></label><button className="primary-action" onClick={p.saveSendung}><Save size={16}/> Speichern</button>{p.notice && <p className="notice">{p.notice}</p>}</article></section> }
function Kalender({ preview, settings, setSettings }: { preview: string[][]; settings: AppSettings; setSettings: (s: AppSettings) => void }) { return <section className="workspace-grid"><article className="panel form-panel"><div className="panel-header"><div><p className="eyebrow">Zeitraum</p><h3>Exportzeitraum einstellen</h3></div></div><label>Von<input type="date" value={settings.periodStart} onChange={(e) => setSettings({...settings, periodStart: e.target.value})}/></label><label>Bis<input type="date" value={settings.periodEnd} onChange={(e) => setSettings({...settings, periodEnd: e.target.value})}/></label><label>Ansicht<select value={settings.viewMode} onChange={(e) => setSettings({...settings, viewMode: e.target.value as AppSettings['viewMode']})}><option>Tag</option><option>Woche</option><option>Monat</option></select></label></article><article className="panel"><div className="panel-header"><div><p className="eyebrow">{settings.viewMode}ansicht</p><h3>Export-Vorschau</h3></div></div><Preview rows={preview}/></article></section> }
function Publikation(p: { exportTxt: () => void; exportJson: () => void; exportAffinity: () => void; exportXml: () => void; exportHtml: () => void; exportRds: () => void }) { return <article className="panel"><div className="panel-header"><div><p className="eyebrow">Publikation</p><h3>Export erstellen</h3></div></div><div className="export-actions"><button className="primary-action" onClick={p.exportTxt}><Download size={16}/> TXT</button><button className="ghost-action" onClick={p.exportAffinity}>Affinity Tags</button><button className="ghost-action" onClick={p.exportXml}>XML / InDesign</button><button className="ghost-action" onClick={p.exportHtml}>HTML</button><button className="ghost-action" onClick={p.exportRds}>RDS</button><button className="ghost-action" onClick={p.exportJson}>JSON</button></div></article> }
function Einstellungen({ settings, setSettings, reset }: { settings: AppSettings; setSettings: (s: AppSettings) => void; reset: () => void }) { function load(file?: File) { if (!file) return; const reader = new FileReader(); reader.onload = () => setSettings({...settings, logoImage: String(reader.result)}); reader.readAsDataURL(file) } return <section className="workspace-grid"><article className="panel form-panel"><div className="panel-header"><div><p className="eyebrow">Allgemein</p><h3>Organisation</h3></div></div><label>Organisationsname<input value={settings.organisationName} onChange={(e) => setSettings({...settings, organisationName: e.target.value})}/></label><label>Sprache der Oberfläche<select value={settings.language} onChange={(e) => setSettings({...settings, language: e.target.value as AppSettings['language']})}><option value="de">Deutsch</option><option value="it">Italiano</option><option value="en">English</option></select></label><label>Logo Bild<input type="file" accept="image/png,image/jpeg,image/webp,image/svg+xml" onChange={(e) => load(e.target.files?.[0])}/></label><label>Logo Text<input value={settings.logoText} onChange={(e) => setSettings({...settings, logoText: e.target.value})}/></label><button className="ghost-action" onClick={() => setSettings({...settings, logoImage: ''})}>Bild entfernen</button><button className="danger-button" onClick={reset}>Lokale Daten zurücksetzen</button></article><article className="panel"><div className="panel-header"><div><p className="eyebrow">Vorschau</p><h3>Logo</h3></div></div><div className="logo-preview">{settings.logoImage ? <img src={settings.logoImage} alt="Logo"/> : <span>{settings.logoText}</span>}</div><p className="muted">Wenn kein Bild vorhanden ist, wird der Logo-Text verwendet.</p></article></section> }
