import { useEffect, useMemo, useState } from 'react'
import { CalendarDays, Download, FileUp, Home, Pencil, Radio, Repeat, Save, Search, Settings, Trash2 } from 'lucide-react'
import { scheduleRules, sendungen as seedSendungen, type Sendung } from './data/seed'

type Lang = 'de' | 'it' | 'en'
type Page = 'dashboard' | 'sendungen' | 'wiederkehrend' | 'wochenprogramm' | 'kalender' | 'import' | 'publikation' | 'einstellungen'
type PeriodMode = 'monat' | 'bimonat' | 'jahr' | 'frei'
type ViewMode = 'Tag' | 'Woche' | 'Monat'
type Form = Omit<Sendung, 'id'> & { id?: string }
type ProgramRow = { id: string; date: string; day: string; time: string; title: string; info: string; source: 'regel' | 'woche' | 'import' }
type AppSettings = { organisationName: string; language: Lang; logoText: string; logoImage: string; periodMode: PeriodMode; periodStart: string; periodEnd: string; viewMode: ViewMode }

const defaults: AppSettings = { organisationName: 'Radio Maria Südtirol', language: 'de', logoText: 'R', logoImage: '', periodMode: 'bimonat', periodStart: '2023-11-01', periodEnd: '2023-12-31', viewMode: 'Woche' }
const emptyForm: Form = { title: '', category: '', language: 'de', source: 'local', active: true }
const emptyProgram: ProgramRow = { id: '', date: '2023-11-01', day: 'Mittwoch', time: '08:00', title: '', info: '', source: 'woche' }
const manualSeed: ProgramRow[] = [{ id: 'sp_2023_12_02_0900', date: '2023-12-02', day: 'Samstag', time: '09:00', title: 'Adventtreffen', info: 'Sonderprogramm', source: 'woche' }]
const t = {
  de: { dashboard:'Dashboard', sendungen:'Sendungen', wiederkehrend:'Wiederkehrend', wochenprogramm:'Wochenprogramm', kalender:'Kalender', import:'Import', publikation:'Publikation', einstellungen:'Einstellungen', new:'Neue Sendung', period:'Exportzeitraum', preview:'Export-Vorschau', save:'Speichern', search:'Suchen', edit:'Bearbeiten', delete:'Löschen' },
  it: { dashboard:'Dashboard', sendungen:'Trasmissioni', wiederkehrend:'Ricorrenti', wochenprogramm:'Settimanali', kalender:'Calendario', import:'Importazione', publikation:'Esportazione', einstellungen:'Impostazioni', new:'Nuova trasmissione', period:'Periodo di esportazione', preview:'Anteprima export', save:'Salva', search:'Cerca', edit:'Modifica', delete:'Elimina' },
  en: { dashboard:'Dashboard', sendungen:'Shows', wiederkehrend:'Recurring', wochenprogramm:'Weekly', kalender:'Calendar', import:'Import', publikation:'Export', einstellungen:'Settings', new:'New show', period:'Export period', preview:'Export preview', save:'Save', search:'Search', edit:'Edit', delete:'Delete' },
}
const pages: { id: Page; icon: typeof Home }[] = [{ id:'dashboard', icon:Home }, { id:'sendungen', icon:Radio }, { id:'wiederkehrend', icon:Repeat }, { id:'wochenprogramm', icon:CalendarDays }, { id:'kalender', icon:CalendarDays }, { id:'import', icon:FileUp }, { id:'publikation', icon:Download }, { id:'einstellungen', icon:Settings }]
const deDays = ['Sonntag','Montag','Dienstag','Mittwoch','Donnerstag','Freitag','Samstag']
const dayCodes = ['SU','MO','TU','WE','TH','FR','SA']
function makeId(title: string) { return `snd_${title.toLowerCase().replaceAll(' ', '_')}` }
function saveFile(name: string, content: string, type = 'text/plain;charset=utf-8') { const blob = new Blob([content], { type }); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = name; a.click(); URL.revokeObjectURL(url) }
function datesBetween(start: string, end: string) { const out: Date[] = []; const a = new Date(`${start}T00:00:00`); const b = new Date(`${end}T00:00:00`); for (let d = a; d <= b; d.setDate(d.getDate() + 1)) out.push(new Date(d)); return out }
function iso(d: Date) { return d.toISOString().slice(0,10) }
function dayName(date: string) { return deDays[new Date(`${date}T00:00:00`).getDay()] }
function monthName(date: string) { return new Intl.DateTimeFormat('de-DE', { month: 'long', year: 'numeric' }).format(new Date(`${date}T00:00:00`)) }
function setPeriod(mode: PeriodMode, settings: AppSettings): AppSettings { const s = new Date(`${settings.periodStart}T00:00:00`); const e = new Date(s); if (mode === 'monat') e.setMonth(s.getMonth() + 1, 0); if (mode === 'bimonat') e.setMonth(s.getMonth() + 2, 0); if (mode === 'jahr') e.setFullYear(s.getFullYear(), 11, 31); return { ...settings, periodMode: mode, periodEnd: mode === 'frei' ? settings.periodEnd : iso(e) } }
function grouped(rows: ProgramRow[]) { return rows.reduce<Record<string, ProgramRow[]>>((acc, row) => { const key = `${row.date}|${row.day}`; acc[key] = [...(acc[key] || []), row]; return acc }, {}) }

export function App() {
  const [page, setPage] = useState<Page>('dashboard')
  const [query, setQuery] = useState('')
  const [form, setForm] = useState<Form>(emptyForm)
  const [programForm, setProgramForm] = useState<ProgramRow>(emptyProgram)
  const [notice, setNotice] = useState('')
  const [sendungen, setSendungen] = useState<Sendung[]>(() => JSON.parse(localStorage.getItem('rms.sendungen') || 'null') || seedSendungen)
  const [manualRows, setManualRows] = useState<ProgramRow[]>(() => JSON.parse(localStorage.getItem('rms.manualRows') || 'null') || manualSeed)
  const [settings, setSettings] = useState<AppSettings>(() => ({ ...defaults, ...(JSON.parse(localStorage.getItem('rms.settings') || 'null') || {}) }))
  const L = t[settings.language]
  useEffect(() => localStorage.setItem('rms.sendungen', JSON.stringify(sendungen)), [sendungen])
  useEffect(() => localStorage.setItem('rms.manualRows', JSON.stringify(manualRows)), [manualRows])
  useEffect(() => localStorage.setItem('rms.settings', JSON.stringify(settings)), [settings])
  const filtered = useMemo(() => sendungen.filter((s) => `${s.title} ${s.category} ${s.source}`.toLowerCase().includes(query.toLowerCase())), [sendungen, query])
  const generated = useMemo(() => datesBetween(settings.periodStart, settings.periodEnd).flatMap((date) => scheduleRules.filter((r) => r.active && r.weekdays.includes(dayCodes[date.getDay()])).map((r) => { const s = sendungen.find((x) => x.id === r.sendungId); const d = iso(date); return { id: `${d}_${r.id}`, date: d, day: dayName(d), time: r.startTime, title: s?.title || r.title || r.sendungId, info: 'Regel', source: 'regel' as const } })), [settings.periodStart, settings.periodEnd, sendungen])
  const preview = useMemo(() => [...generated, ...manualRows.filter((r) => r.date >= settings.periodStart && r.date <= settings.periodEnd)].sort((a,b) => `${a.date}${a.time}`.localeCompare(`${b.date}${b.time}`)), [generated, manualRows, settings.periodStart, settings.periodEnd])
  function editSendung(s: Sendung) { setPage('sendungen'); setForm(s); setNotice('Sendung wird bearbeitet.') }
  function saveSendung() { if (!form.title.trim()) return setNotice('Bitte einen Titel eingeben.'); const item: Sendung = { id: form.id || makeId(form.title), title: form.title.trim(), category: form.category || 'Ohne Kategorie', language: form.language, source: form.source || 'local', active: form.active }; setSendungen(sendungen.some((s) => s.id === item.id) ? sendungen.map((s) => s.id === item.id ? item : s) : [item, ...sendungen]); setForm(emptyForm); setNotice('Sendung gespeichert.') }
  function saveProgram() { if (!programForm.title.trim()) return setNotice('Titel fehlt.'); const row = { ...programForm, id: programForm.id || `row_${Date.now()}`, day: dayName(programForm.date), source: 'woche' as const }; setManualRows(manualRows.some((r) => r.id === row.id) ? manualRows.map((r) => r.id === row.id ? row : r) : [row, ...manualRows]); setProgramForm(emptyProgram); setNotice('Programmpunkt gespeichert.') }
  function importCsv(text: string) { const lines = text.split(/\r?\n/).filter(Boolean); const parsed = lines.slice(lines[0]?.toLowerCase().includes('datum') ? 1 : 0).map((line, i) => { const c = line.split(/[;\t,]/); const date = c[0] || settings.periodStart; return { id: `imp_${Date.now()}_${i}`, date, day: c[1] || dayName(date), time: c[2] || '00:00', title: c[3] || 'Ohne Titel', info: c[4] || '', source: 'import' as const } }); setManualRows([...parsed, ...manualRows]); setNotice(`${parsed.length} Zeilen importiert.`) }
  function exportText(kind: 'txt'|'affinity'|'xml'|'html'|'rds'|'json') { const groups = grouped(preview); const block = Object.entries(groups).map(([key, rows]) => { const [date, day] = key.split('|'); return `${monthName(date)}\n${day}, ${date}\n${rows.map((r) => `${r.time} ${r.title}${r.info ? ` - ${r.info}` : ''}`).join('\n')}` }).join('\n\n'); if (kind === 'txt') saveFile('programmheft.txt', block); if (kind === 'affinity') saveFile('affinity-tags.txt', Object.entries(groups).map(([key, rows]) => { const [date, day] = key.split('|'); return `<Monat>${monthName(date)}</Monat>\n<Datum>${date}</Datum>\n<Tag>${day}</Tag>\n${rows.map((r) => `<Uhrzeit>${r.time}</Uhrzeit><Sendung>${r.title}</Sendung><Info>${r.info}</Info>`).join('\n')}` }).join('\n\n')); if (kind === 'xml') saveFile('programm.xml', `<programm von="${settings.periodStart}" bis="${settings.periodEnd}">${preview.map((r) => `<sendung monat="${monthName(r.date)}" datum="${r.date}" tag="${r.day}" uhrzeit="${r.time}"><titel>${r.title}</titel><info>${r.info}</info></sendung>`).join('')}</programm>`, 'application/xml'); if (kind === 'html') saveFile('programm.html', Object.entries(groups).map(([key, rows]) => { const [date, day] = key.split('|'); return `<section><h2>${day}, ${date}</h2>${rows.map((r) => `<p><b>${r.time}</b> ${r.title} ${r.info}</p>`).join('')}</section>` }).join(''), 'text/html'); if (kind === 'rds') saveFile('rds.txt', preview.map((r) => `${r.time}|${r.title}`).join('\n')); if (kind === 'json') saveFile('programm.json', JSON.stringify({ settings, preview }, null, 2), 'application/json') }
  return <main className="app-shell"><aside className="sidebar"><div className="brand-block"><div className="brand-mark">{settings.logoImage ? <img src={settings.logoImage} alt="Logo"/> : settings.logoText}</div><div><p className="eyebrow">{settings.organisationName}</p><h1>RMS</h1></div></div><nav className="navigation">{pages.map((p) => { const Icon = p.icon; return <button key={p.id} className={page === p.id ? 'nav-item active' : 'nav-item'} onClick={() => setPage(p.id)}><Icon size={18}/><span>{L[p.id]}</span></button> })}</nav><div className="sidebar-card"><p>{L.period}</p><strong>{settings.periodStart} bis {settings.periodEnd}</strong></div></aside><section className="content-area"><header className="topbar"><div><p className="eyebrow">RMS</p><h2>{L[page]}</h2></div><button className="primary-action" onClick={() => { setPage('sendungen'); setForm(emptyForm) }}>{L.new}</button></header>{page === 'dashboard' && <Dashboard L={L} preview={preview} sendungen={sendungen} openCalendar={() => setPage('kalender')} editSendung={editSendung}/>} {page === 'sendungen' && <Sendungen L={L} filtered={filtered} query={query} setQuery={setQuery} form={form} setForm={setForm} saveSendung={saveSendung} deleteSendung={(id) => setSendungen(sendungen.filter((s) => s.id !== id))} editSendung={editSendung} notice={notice}/>} {page === 'wiederkehrend' && <Recurring />} {page === 'wochenprogramm' && <Weekly form={programForm} setForm={setProgramForm} save={saveProgram} rows={manualRows} edit={setProgramForm} remove={(id) => setManualRows(manualRows.filter((r) => r.id !== id))}/>} {page === 'kalender' && <Kalender L={L} preview={preview} settings={settings} setSettings={setSettings}/>} {page === 'import' && <Import importCsv={importCsv} notice={notice}/>} {page === 'publikation' && <Publikation exportText={exportText}/>} {page === 'einstellungen' && <Einstellungen settings={settings} setSettings={setSettings} reset={() => { localStorage.clear(); location.reload() }}/>}</section></main>
}
function Preview({ rows }: { rows: ProgramRow[] }) { const groups = grouped(rows); return <div className="timeline">{Object.entries(groups).map(([key, items]) => { const [date, day] = key.split('|'); return <div key={key} className="table-row"><div><strong>{day}, {date}</strong>{items.map((r) => <p key={r.id}><b>{r.time}</b> {r.title} {r.info}</p>)}</div></div> })}</div> }
function Dashboard({ L, preview, sendungen, openCalendar, editSendung }: { L: typeof t.de; preview: ProgramRow[]; sendungen: Sendung[]; openCalendar: () => void; editSendung: (s: Sendung) => void }) { return <><section className="hero-panel"><div><p className="eyebrow">{L.period}</p><h3>Programmheft November-Dezember</h3><p>{preview.length} Programmpunkte in der aktuellen Vorschau.</p></div><button className="hero-action" onClick={openCalendar}>{L.kalender}</button></section><section className="main-grid"><article className="panel"><div className="panel-header"><div><p className="eyebrow">{L.preview}</p><h3>Gruppiert nach Wochentag</h3></div></div><Preview rows={preview.slice(0,12)}/></article><article className="panel"><div className="panel-header"><div><p className="eyebrow">{L.sendungen}</p><h3>Katalog</h3></div></div><div className="sendung-list">{sendungen.slice(0,8).map((s) => <button className="sendung-row" key={s.id} onClick={() => editSendung(s)}><div><strong>{s.title}</strong><p>{s.category}</p></div><span>{s.source}</span></button>)}</div></article></section></> }
function Sendungen(p: { L: typeof t.de; filtered: Sendung[]; query: string; setQuery: (v: string) => void; form: Form; setForm: (f: Form) => void; saveSendung: () => void; deleteSendung: (id: string) => void; editSendung: (s: Sendung) => void; notice: string }) { return <section className="workspace-grid"><article className="panel"><div className="panel-header"><div><p className="eyebrow">Katalog</p><h3>Sendungen verwalten</h3></div><div className="search-box"><Search size={16}/><input value={p.query} onChange={(e) => p.setQuery(e.target.value)} placeholder={p.L.search}/></div></div><div className="table-list">{p.filtered.map((s) => <div className="table-row" key={s.id}><div><strong>{s.title}</strong><p>{s.category} · {s.source}</p></div><div className="row-actions"><button onClick={() => p.editSendung(s)}><Pencil size={16}/> {p.L.edit}</button><button className="danger" onClick={() => p.deleteSendung(s.id)}><Trash2 size={16}/> {p.L.delete}</button></div></div>)}</div></article><article className="panel form-panel"><h3>{p.form.id ? 'Sendung bearbeiten' : p.L.new}</h3><label>Titel<input value={p.form.title} onChange={(e) => p.setForm({...p.form, title: e.target.value})}/></label><label>Kategorie<input value={p.form.category} onChange={(e) => p.setForm({...p.form, category: e.target.value})}/></label><label>Quelle<input value={p.form.source} onChange={(e) => p.setForm({...p.form, source: e.target.value})}/></label><button className="primary-action" onClick={p.saveSendung}><Save size={16}/> {p.L.save}</button>{p.notice && <p className="notice">{p.notice}</p>}</article></section> }
function Recurring() { return <article className="panel"><div className="panel-header"><div><p className="eyebrow">Regeln</p><h3>Normale wiederkehrende Sendungen</h3></div></div><div className="table-list">{scheduleRules.map((r) => <div className="table-row" key={r.id}><div><strong>{r.startTime} · {seedSendungen.find((s) => s.id === r.sendungId)?.title || r.sendungId}</strong><p>{r.weekdays.join(', ')}</p></div><span className="tag">{r.active ? 'Aktiv' : 'Inaktiv'}</span></div>)}</div></article> }
function Weekly({ form, setForm, save, rows, edit, remove }: { form: ProgramRow; setForm: (r: ProgramRow) => void; save: () => void; rows: ProgramRow[]; edit: (r: ProgramRow) => void; remove: (id: string) => void }) { return <section className="workspace-grid"><article className="panel form-panel"><h3>Einzelne / wöchentliche Programmpunkte</h3><label>Datum<input type="date" value={form.date} onChange={(e) => setForm({...form, date: e.target.value})}/></label><label>Uhrzeit<input value={form.time} onChange={(e) => setForm({...form, time: e.target.value})}/></label><label>Titel<input value={form.title} onChange={(e) => setForm({...form, title: e.target.value})}/></label><label>Info<input value={form.info} onChange={(e) => setForm({...form, info: e.target.value})}/></label><button className="primary-action" onClick={save}>Speichern</button></article><article className="panel"><div className="table-list">{rows.map((r) => <div className="table-row" key={r.id}><div><strong>{r.day}, {r.date}</strong><p>{r.time} {r.title} {r.info}</p></div><div className="row-actions"><button onClick={() => edit(r)}>Bearbeiten</button><button className="danger" onClick={() => remove(r.id)}>Löschen</button></div></div>)}</div></article></section> }
function Kalender({ L, preview, settings, setSettings }: { L: typeof t.de; preview: ProgramRow[]; settings: AppSettings; setSettings: (s: AppSettings) => void }) { return <section className="workspace-grid"><article className="panel form-panel"><h3>{L.period}</h3><label>Preset<select value={settings.periodMode} onChange={(e) => setSettings(setPeriod(e.target.value as PeriodMode, settings))}><option value="monat">Monat</option><option value="bimonat">Bimestre</option><option value="jahr">Jahr</option><option value="frei">Freier Zeitraum</option></select></label><label>Von<input type="date" value={settings.periodStart} onChange={(e) => setSettings(setPeriod(settings.periodMode, {...settings, periodStart: e.target.value}))}/></label><label>Bis<input type="date" value={settings.periodEnd} onChange={(e) => setSettings({...settings, periodEnd: e.target.value, periodMode: 'frei'})}/></label><label>Ansicht<select value={settings.viewMode} onChange={(e) => setSettings({...settings, viewMode: e.target.value as ViewMode})}><option>Tag</option><option>Woche</option><option>Monat</option></select></label></article><article className="panel"><div className="panel-header"><div><p className="eyebrow">{settings.viewMode}</p><h3>{L.preview}</h3></div></div><Preview rows={preview}/></article></section> }
function Import({ importCsv, notice }: { importCsv: (text: string) => void; notice: string }) { return <article className="panel form-panel"><h3>CSV aus Excel importieren</h3><p className="muted">Spalten: Datum; Wochentag; Uhrzeit; Sendung; Info</p><input type="file" accept=".csv,.tsv,.txt" onChange={(e) => { const file = e.target.files?.[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => importCsv(String(reader.result || '')); reader.readAsText(file) }}/>{notice && <p className="notice">{notice}</p>}</article> }
function Publikation({ exportText }: { exportText: (k: 'txt'|'affinity'|'xml'|'html'|'rds'|'json') => void }) { return <article className="panel"><div className="panel-header"><div><p className="eyebrow">Publikation</p><h3>Export erstellen</h3></div></div><div className="export-actions"><button className="primary-action" onClick={() => exportText('txt')}>TXT</button><button className="ghost-action" onClick={() => exportText('affinity')}>Affinity Tags</button><button className="ghost-action" onClick={() => exportText('xml')}>XML / InDesign</button><button className="ghost-action" onClick={() => exportText('html')}>HTML</button><button className="ghost-action" onClick={() => exportText('rds')}>RDS</button><button className="ghost-action" onClick={() => exportText('json')}>JSON</button></div></article> }
function Einstellungen({ settings, setSettings, reset }: { settings: AppSettings; setSettings: (s: AppSettings) => void; reset: () => void }) { function load(file?: File) { if (!file) return; const reader = new FileReader(); reader.onload = () => setSettings({...settings, logoImage: String(reader.result)}); reader.readAsDataURL(file) } return <section className="workspace-grid"><article className="panel form-panel"><h3>Organisation</h3><label>Organisationsname<input value={settings.organisationName} onChange={(e) => setSettings({...settings, organisationName: e.target.value})}/></label><label>Sprache der Oberfläche<select value={settings.language} onChange={(e) => setSettings({...settings, language: e.target.value as Lang})}><option value="de">Deutsch</option><option value="it">Italiano</option><option value="en">English</option></select></label><label>Logo Bild<input type="file" accept="image/png,image/jpeg,image/webp,image/svg+xml" onChange={(e) => load(e.target.files?.[0])}/></label><label>Logo Text<input value={settings.logoText} onChange={(e) => setSettings({...settings, logoText: e.target.value})}/></label><button className="ghost-action" onClick={() => setSettings({...settings, logoImage: ''})}>Bild entfernen</button><button className="danger-button" onClick={reset}>Lokale Daten zurücksetzen</button></article><article className="panel"><h3>Logo</h3><div className="logo-preview">{settings.logoImage ? <img src={settings.logoImage} alt="Logo"/> : <span>{settings.logoText}</span>}</div><p className="muted">Wenn kein Bild vorhanden ist, wird der Logo-Text verwendet.</p></article></section> }
